//
//  AuthenticationView.swift
//  Simple Store
//

import SwiftUI
import FirebaseAuth
import FirebaseFirestore

// MARK: - View Model

/// Manages the business logic and state for the authentication workflow.
///
/// Encapsulates Firebase Authentication and Firestore provisioning to ensure
/// strict `@MainActor` isolation and multi-tenant workspace initialization.
@MainActor
@Observable
final class AuthenticationViewModel {
    /// The current mode of the authentication form.
    enum Mode {
        case login
        case register
        
        var toggleText: String {
            self == .login ? "Don't have an account? Sign up" : "Already have an account? Sign in"
        }
        
        var actionText: String {
            self == .login ? "Sign In" : "Create Account"
        }
        
        var headerSubtitle: String {
            self == .login ? "Sign in to access your store" : "Create an account to get started"
        }
    }
    
    var mode: Mode = .login
    var email = ""
    var password = ""
    var fullName = ""
    var errorMessage: String? = nil
    var isProcessing = false
    
    /// Validates the current form state based on the active authentication mode.
    var isFormValid: Bool {
        let emailValid = email.isValidEmail
        let passwordValid = password.count >= 6
        
        if mode == .login {
            return emailValid && passwordValid
        } else {
            return emailValid && passwordValid && !fullName.trimmingCharacters(in: .whitespaces).isEmpty
        }
    }
    
    /// Executes the authentication flow, creating or logging in the user, and provisioning initial data.
    /// - Parameter session: The global session manager to update upon success.
    func authenticate(session: SessionManager) async {
        isProcessing = true
        errorMessage = nil
        
        defer {
            isProcessing = false
        }
        
        do {
            if mode == .login {
                try await Auth.auth().signIn(withEmail: email, password: password)
            } else {
                let result = try await Auth.auth().createUser(withEmail: email, password: password)
                try await provisionNewUser(uid: result.user.uid)
            }
            
            // Re-added the await keyword as required by the compiler.
            await session.checkAuthenticationState()
        } catch {
            errorMessage = error.localizedDescription
        }
    }
    
    /// Provisions a new user document in Firestore with multi-tenant capabilities.
    /// - Parameter uid: The unique identifier generated by Firebase Auth.
    private func provisionNewUser(uid: String) async throws {
        let newUser = AppUser(
            id: uid,
            name: fullName,
            email: email,
            phone: "",
            isSystemAdmin: false,
            storeIds: [],
            storeRoles: [:],
            activeStoreId: nil,
            autoJoinStoreId: nil
        )
        
        let db = Firestore.firestore()
        let userData = try Firestore.Encoder().encode(newUser)
        try await db.collection("users").document(uid).setData(userData)
    }
    
    /// Toggles between login and registration modes, clearing any transient errors.
    func toggleMode() {
        withAnimation(.snappy) {
            mode = mode == .login ? .register : .login
            errorMessage = nil
        }
    }
}

// MARK: - View

/// The primary authentication interface for the Simple Store ecosystem.
struct AuthenticationView: View {
    @Environment(SessionManager.self) private var session
    @State private var viewModel = AuthenticationViewModel()
    
    var body: some View {
        NavigationStack {
            ScrollView {
                VStack(spacing: 32) {
                    headerSection
                    formSection
                    actionSection
                }
                .padding(.vertical, 40)
            }
            .scrollDismissesKeyboard(.interactively)
            .background(Color(uiColor: .systemBackground))
        }
    }
    
    // MARK: - Subviews
    
    private var headerSection: some View {
        VStack(spacing: 12) {
            Image(systemName: "storefront.circle.fill")
                .font(.system(size: 80))
                .foregroundStyle(Color.accentColor)
            
            Text("Simple Store")
                .font(.largeTitle)
                .fontWeight(.heavy)
            
            Text(viewModel.mode.headerSubtitle)
                .font(.subheadline)
                .foregroundStyle(.secondary)
        }
    }
    
    private var formSection: some View {
        VStack(spacing: 16) {
            if viewModel.mode == .register {
                TextField("Full Name", text: $viewModel.fullName)
                    .textContentType(.name)
                    .modifier(AuthFieldModifier())
            }
            
            TextField("Email Address", text: $viewModel.email)
                .keyboardType(.emailAddress)
                .textContentType(.emailAddress)
                .textInputAutocapitalization(.never)
                .autocorrectionDisabled()
                .modifier(AuthFieldModifier())
            
            SecureField("Password (min 6 characters)", text: $viewModel.password)
                .textContentType(viewModel.mode == .login ? .password : .newPassword)
                .modifier(AuthFieldModifier())
            
            if let errorMessage = viewModel.errorMessage {
                Text(errorMessage)
                    .font(.caption)
                    .foregroundStyle(.red)
                    .multilineTextAlignment(.center)
                    .transition(.opacity)
            }
        }
        .padding(.horizontal, 24)
        .animation(.snappy, value: viewModel.mode)
    }
    
    private var actionSection: some View {
        VStack(spacing: 16) {
            Button {
                Task {
                    await viewModel.authenticate(session: session)
                }
            } label: {
                ZStack {
                    if viewModel.isProcessing {
                        ProgressView()
                            .tint(.white)
                    } else {
                        Text(viewModel.mode.actionText)
                    }
                }
                .font(.headline)
                .frame(maxWidth: .infinity)
                .padding()
                .background(viewModel.isFormValid ? Color.accentColor : Color(uiColor: .systemGray4))
                .foregroundStyle(.white)
                .clipShape(RoundedRectangle(cornerRadius: 12, style: .continuous))
            }
            .disabled(!viewModel.isFormValid || viewModel.isProcessing)
            
            Button(action: viewModel.toggleMode) {
                Text(viewModel.mode.toggleText)
                    .font(.subheadline)
                    .foregroundStyle(Color.accentColor)
            }
            .disabled(viewModel.isProcessing)
        }
        .padding(.horizontal, 24)
    }
}

// MARK: - Modifiers

/// A standard view modifier to enforce consistent styling across authentication input fields.
private struct AuthFieldModifier: ViewModifier {
    func body(content: Content) -> some View {
        content
            .padding()
            .background(Color(uiColor: .secondarySystemBackground))
            .clipShape(RoundedRectangle(cornerRadius: 12, style: .continuous))
    }
}
